name: dummy CD workflow

on:
 workflow_dispatch:
    inputs:
      env:
        type: choice
        options:
          - dev
        description: "which environment to deploy to"
        required: true

      image-tags:
        type: string
        description: "what images to deploy (non-empty json string {image-name: image-tag, ...})"
        required: true
jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: |
          echo "env is ${{ github.event.inputs.env }}"
          echo "image-tags is ${{ github.event.inputs.images }}"
